### ISSUE TITLE
Update navbar classes

### ISSUE THREAD

**Issue by stroup-tmu** [Zwilson1301/Book_track#4]
The classes for the navbar for adapting to the light/dark mode should be as follows:

`navbar navbar-expand-lg bg-body-tertiary`

https://github.com/Zwilson1301/Book_track/blob/36066980bf216f5ee246ff7fc20a8a61b38aab56/app/views/layouts/application.html.erb#L16

**Comment by stroup-tmu** [comment]
(no need for navbar-light or bg-dark)

**Comment by Zwilson1301** [comment]
ok
