### ISSUE TITLE
Move navbar code to partial

### ISSUE THREAD

**Issue by stroup-tmu** [Zwilson1301/Book_track#5]
Also, for DRY code (Don't Repeat Yourself), you need to move the navbar to a partial (e.g. app/views/shared/_navbar.html.erb), and then render it from the layout like this:

<%= render "shared/navbar" %>

Take a look at the student LMS if you need help!

https://github.com/Zwilson1301/Book_track/blob/36066980bf216f5ee246ff7fc20a8a61b38aab56/app/views/layouts/application.html.erb#L16

**Comment by Zwilson1301** [comment]
done
